### ISSUE TITLE
pm25 有没有什么roadmap？未来要怎么做，添加那些功能？

### ISSUE THREAD

**Issue by elover** [PaulGuo/PM25#3]

**Comment by PaulGuo** [comment]
![](http://ww2.sinaimg.cn/large/62755f82jw1ezyd8xkgqhj20bz05nglt.jpg)

近期准备迭代的功能点：自定义操作、内存泄露预警、内存/CPU辅助分析

**Comment by PaulGuo** [comment]
@elover 如果有需求也可以提出来或者参与进来。:)

**Comment by cgx9** [comment]
@PaulGuo 希望可以基于整个应用来看日志，而不仅仅基于进程。毕竟进程是自动分发，有时查问题没那么方便。我看文档是基于进程？最好还能看其他类型日志。只要是code里输出的。

**Comment by PaulGuo** [comment]
新增CPU Profile和Heapdump分析功能支持，如图所示：
![cpu profile heapdump](https://cloud.githubusercontent.com/assets/758740/13258472/3c9c1986-da8e-11e5-91a7-399103057daf.png)

@cgx9 基于应用查看日志可以直接借助pm2/pm25命令行，PM25控制台侧重的是进程维度细粒度的指标展示、错误以及自定义操作。
