### ISSUE TITLE
有没有详细介绍这个东西怎么用的？

### ISSUE THREAD

**Issue by leovs** [PaulGuo/PM25#4]

**Comment by cgx9** [comment]
文档代码有，也可以见：http://pm25.io/docs/ 主要还是类似pm2的用法，用的是pm25.io的server。

**Comment by PaulGuo** [comment]
文档和使用说明可以暂时参考 [http://pm25.io/docs/](http://pm25.io/docs/)，其余问题欢迎提issue讨论。

**Comment by xuhuan** [comment]
@PaulGuo 目前的文档感觉不全啊，看文档服务端搭不起来。
能否先完善下怎么搭建的文档？让项目能先在自己本地跑起来！
如果跑都跑不起来的话兴趣缺失啊。
