### ISSUE TITLE
项目是否缺少维护人员，后期还能持续维护下去不

### ISSUE THREAD

**Issue by xuhuan** [PaulGuo/PM25#8]
整体项目要解决的问题感觉不错，不过看目前维护人员好像只有1个，而且不少东西都没有完善，不知道项目能否持续发展下去。
顺带问下项目已经在生产环境运行了嘛？稳定性怎么样？

**Comment by PaulGuo** [comment]
目前已经用于我们内部多个部门多个业务线生产环境的Node服务监控，也已经帮助解决了多例线上问题，目前主要是我一个人在负责功能维护和开发，更多的需求来自我们内部（比如刚刚提交的CPU Profile和Heapdump生成功能），如果有精力有兴趣欢迎加入一起共建。

**Comment by xuhuan** [comment]
@PaulGuo 昨天尝试过在本地搭建，发现搭建过程有点坑。
cloud搭建不起来，数据库的sql文件也没找到。
能否先提供个完整搭建的说明？
